-- =============================================================================
-- BASE DE DATOS: BOLSO APP (ESPAÑOL)
-- Sistema de Círculos de Ahorro (San / Bolso)
-- =============================================================================

CREATE SCHEMA "san";
CREATE SCHEMA "libro_mayor";
CREATE SCHEMA "finanzas";
CREATE SCHEMA "nucleo";
CREATE SCHEMA "autenticacion";

-- -----------------------------------------------------------------------------
-- TIPOS ENUMERADOS (ENUMS)
-- -----------------------------------------------------------------------------

CREATE TYPE "san"."estado_circulo" AS ENUM (
  'BORRADOR',
  'PENDIENTE',
  'ACTIVO',
  'COMPLETADO',
  'INCUMPLIDO',
  'CANCELADO'
);

CREATE TYPE "san"."estado_ronda" AS ENUM (
  'PENDIENTE',
  'EN_RECAUDACION',
  'LISTO_PARA_PAGO',
  'PAGADO',
  'VENCIDO'
);

CREATE TYPE "san"."estado_pago" AS ENUM (
  'PENDIENTE',
  'CONFIRMADO',
  'RECHAZADO'
);

CREATE TYPE "libro_mayor"."direccion_asiento" AS ENUM (
  'DEBITO',
  'CREDITO'
);

-- -----------------------------------------------------------------------------
-- TABLAS DEL ESQUEMA SAN (CÍRCULOS DE AHORRO)
-- -----------------------------------------------------------------------------

CREATE TABLE "san"."circulos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_administrador" int NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "codigo_invitacion" varchar(16) UNIQUE NOT NULL,
  "monto_contribucion" decimal(12,2) NOT NULL,
  "id_moneda" int NOT NULL,
  "total_turnos" smallint NOT NULL,
  "frecuencia_dias" smallint DEFAULT 7,
  "porcentaje_comision_retiro" decimal(4,2) DEFAULT 2,
  "estado" san.estado_circulo DEFAULT 'PENDIENTE'
);

CREATE TABLE "san"."miembros_circulo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_circulo" int NOT NULL,
  "id_usuario" int NOT NULL,
  "numero_turno" smallint NOT NULL
);

CREATE TABLE "san"."rondas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_circulo" int NOT NULL,
  "numero_ronda" smallint NOT NULL,
  "id_beneficiario" int NOT NULL,
  "monto_objetivo" decimal(12,2) NOT NULL,
  "monto_comision_pago" decimal(12,2) DEFAULT 0,
  "fecha_inicio" timestamptz NOT NULL,
  "fecha_vencimiento" timestamptz NOT NULL,
  "estado" san.estado_ronda DEFAULT 'PENDIENTE'
);

CREATE TABLE "san"."pagos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_ronda" int NOT NULL,
  "id_usuario" int NOT NULL,
  "id_metodo_pago_usuario" int NOT NULL,
  "monto_nominal" decimal(12,2) NOT NULL,
  "id_moneda" int NOT NULL,
  "monto_equivalente_usd" decimal(12,2) NOT NULL,
  "tasa_cambio_utilizada" decimal(12,4),
  "codigo_referencia" varchar(100) NOT NULL,
  "url_comprobante" text,
  "estado" san.estado_pago DEFAULT 'PENDIENTE',
  "clave_idempotencia" varchar(64) UNIQUE NOT NULL,
  "confirmado_en" timestamptz
);

-- -----------------------------------------------------------------------------
-- TABLAS DEL ESQUEMA LIBRO_MAYOR (CONTABILIDAD Y AUDITORÍA)
-- -----------------------------------------------------------------------------

CREATE TABLE "libro_mayor"."cuentas_contables" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int,
  "id_moneda" int NOT NULL,
  "codigo_cuenta" varchar(64) UNIQUE NOT NULL,
  "descripcion" varchar(255) NOT NULL
);

CREATE TABLE "libro_mayor"."transacciones_contables" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_circulo" int,
  "id_pago" int UNIQUE,
  "descripcion" varchar(255) NOT NULL
);

CREATE TABLE "libro_mayor"."asientos_contables" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_transaccion" int NOT NULL,
  "id_cuenta" int NOT NULL,
  "direccion" libro_mayor.direccion_asiento NOT NULL,
  "monto" decimal(12,2) NOT NULL
);

-- -----------------------------------------------------------------------------
-- TABLAS DEL ESQUEMA FINANZAS (CATÁLOGOS Y MÉTODOS DE PAGO)
-- -----------------------------------------------------------------------------

CREATE TABLE "finanzas"."monedas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(3) UNIQUE NOT NULL,
  "simbolo" varchar(5) NOT NULL,
  "nombre" varchar(50) NOT NULL
);

CREATE TABLE "finanzas"."tipos_metodo_pago" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "finanzas"."metodos_pago_usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int NOT NULL,
  "id_tipo_metodo_pago" int NOT NULL,
  "codigo_banco" varchar(4),
  "numero_telefono" varchar(20),
  "numero_cuenta" varchar(30),
  "direccion_billetera" varchar(255)
);

-- -----------------------------------------------------------------------------
-- TABLAS DEL ESQUEMA NUCLEO (DATOS DE PERSONAS Y CONTACTO / KYC)
-- -----------------------------------------------------------------------------

CREATE TABLE "nucleo"."personas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "primer_nombre" varchar(50) NOT NULL,
  "segundo_nombre" varchar(50),
  "primer_apellido" varchar(50) NOT NULL,
  "segundo_apellido" varchar(50),
  "fecha_nacimiento" date
);

CREATE TABLE "nucleo"."tipos_documento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "nucleo"."documentos_persona" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int NOT NULL,
  "id_tipo_documento" int NOT NULL,
  "numero_documento" varchar(50) NOT NULL
);

CREATE TABLE "nucleo"."tipos_contacto" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "nucleo"."contactos_persona" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int NOT NULL,
  "id_tipo_contacto" int NOT NULL,
  "valor_contacto" varchar(255) NOT NULL
);

CREATE TABLE "nucleo"."direcciones_persona" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int NOT NULL,
  "direccion_calle" text NOT NULL,
  "ciudad" varchar(100),
  "estado" varchar(100),
  "codigo_postal" varchar(20)
);

-- -----------------------------------------------------------------------------
-- TABLAS DEL ESQUEMA AUTENTICACION (USUARIOS Y CREDENCIALES)
-- -----------------------------------------------------------------------------

CREATE TABLE "autenticacion"."usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_persona" int UNIQUE NOT NULL,
  "nombre_usuario" varchar(100) UNIQUE NOT NULL,
  "hash_contrasena" varchar(255) NOT NULL,
  "puntuacion_reputacion" smallint DEFAULT 100
);

CREATE TABLE "autenticacion"."perfiles_sociales_usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int NOT NULL,
  "proveedor" varchar(50) NOT NULL,
  "id_usuario_proveedor" varchar(150) NOT NULL,
  "url_perfil" varchar(255)
);

CREATE TABLE "autenticacion"."referidos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario_referente" int NOT NULL,
  "id_usuario_referido" int UNIQUE NOT NULL,
  "estado" varchar(30) DEFAULT 'PENDIENTE',
  "creado_en" timestamptz DEFAULT (now())
);

-- -----------------------------------------------------------------------------
-- ÍNDICES ÚNICOS
-- -----------------------------------------------------------------------------

CREATE UNIQUE INDEX ON "san"."miembros_circulo" ("id_circulo", "numero_turno");
CREATE UNIQUE INDEX ON "san"."miembros_circulo" ("id_circulo", "id_usuario");
CREATE UNIQUE INDEX ON "san"."rondas" ("id_circulo", "numero_ronda");
CREATE UNIQUE INDEX ON "nucleo"."documentos_persona" ("id_tipo_documento", "numero_documento");
CREATE UNIQUE INDEX ON "autenticacion"."perfiles_sociales_usuario" ("proveedor", "id_usuario_proveedor");

-- -----------------------------------------------------------------------------
-- COMENTARIOS DE TABLAS
-- -----------------------------------------------------------------------------

COMMENT ON TABLE "san"."circulos" IS 'Configuración macro, parámetros financieros y reglas del círculo de ahorro.';
COMMENT ON TABLE "san"."miembros_circulo" IS 'Gestión normalizada de la relación N:M entre usuarios y círculos con asignación de turnos.';
COMMENT ON TABLE "san"."rondas" IS 'Control del calendario y plazos del ciclo transaccional de cada turno.';
COMMENT ON TABLE "san"."pagos" IS 'Registro transaccional de cuotas con separación de montos, monedas y tasas.';

COMMENT ON TABLE "libro_mayor"."cuentas_contables" IS 'Plan contable estructurado por partida doble para auditoría financiera.';
COMMENT ON TABLE "libro_mayor"."transacciones_contables" IS 'Cabecera atómica que agrupa asientos contables equilibrados.';
COMMENT ON TABLE "libro_mayor"."asientos_contables" IS 'Detalle de débitos y créditos individuales; la suma debe cuadrar a cero.';

COMMENT ON TABLE "finanzas"."monedas" IS 'Catálogo normalizado de monedas soportadas.';
COMMENT ON TABLE "finanzas"."tipos_metodo_pago" IS 'Catálogo maestro puro de pasarelas y métodos de pago permitidos.';
COMMENT ON TABLE "finanzas"."metodos_pago_usuario" IS 'Cuentas de cobro y pago configuradas por el usuario para recibir o enviar fondos.';

COMMENT ON TABLE "nucleo"."personas" IS 'Entidad física real desacoplada de la cuenta digital para cumplimiento KYC.';
COMMENT ON TABLE "nucleo"."tipos_documento" IS 'Catálogo de tipos de documentos de identidad oficiales.';
COMMENT ON TABLE "nucleo"."documentos_persona" IS 'Documentos oficiales de identidad múltiples registrados por la persona.';
COMMENT ON TABLE "nucleo"."tipos_contacto" IS 'Catálogo de canales de comunicación soportados.';
COMMENT ON TABLE "nucleo"."contactos_persona" IS 'Canales de comunicación normalizados (correos, teléfonos).';
COMMENT ON TABLE "nucleo"."direcciones_persona" IS 'Ubicaciones físicas y domicilios registrados de la persona.';

COMMENT ON TABLE "autenticacion"."usuarios" IS 'Credenciales de acceso digital y perfil unificado del usuario.';
COMMENT ON TABLE "autenticacion"."perfiles_sociales_usuario" IS 'Permite la vinculación opcional de redes sociales al perfil del usuario.';
COMMENT ON TABLE "autenticacion"."referidos" IS 'Rastrea la red de confianza para evaluar la confiabilidad de nuevos miembros según quién los invitó.';

-- -----------------------------------------------------------------------------
-- CLAVES FORÁNEAS (RELACIONES)
-- -----------------------------------------------------------------------------

ALTER TABLE "nucleo"."documentos_persona" ADD FOREIGN KEY ("id_persona") REFERENCES "nucleo"."personas" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "nucleo"."documentos_persona" ADD FOREIGN KEY ("id_tipo_documento") REFERENCES "nucleo"."tipos_documento" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "nucleo"."contactos_persona" ADD FOREIGN KEY ("id_persona") REFERENCES "nucleo"."personas" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "nucleo"."contactos_persona" ADD FOREIGN KEY ("id_tipo_contacto") REFERENCES "nucleo"."tipos_contacto" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "nucleo"."direcciones_persona" ADD FOREIGN KEY ("id_persona") REFERENCES "nucleo"."personas" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "autenticacion"."usuarios" ADD FOREIGN KEY ("id_persona") REFERENCES "nucleo"."personas" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "autenticacion"."perfiles_sociales_usuario" ADD FOREIGN KEY ("id_usuario") REFERENCES "autenticacion"."usuarios" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "finanzas"."metodos_pago_usuario" ADD FOREIGN KEY ("id_usuario") REFERENCES "autenticacion"."usuarios" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "finanzas"."metodos_pago_usuario" ADD FOREIGN KEY ("id_tipo_metodo_pago") REFERENCES "finanzas"."tipos_metodo_pago" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "san"."circulos" ADD FOREIGN KEY ("id_administrador") REFERENCES "autenticacion"."usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "san"."circulos" ADD FOREIGN KEY ("id_moneda") REFERENCES "finanzas"."monedas" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "san"."miembros_circulo" ADD FOREIGN KEY ("id_circulo") REFERENCES "san"."circulos" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "san"."miembros_circulo" ADD FOREIGN KEY ("id_usuario") REFERENCES "autenticacion"."usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "san"."rondas" ADD FOREIGN KEY ("id_circulo") REFERENCES "san"."circulos" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "san"."rondas" ADD FOREIGN KEY ("id_beneficiario") REFERENCES "autenticacion"."usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "san"."pagos" ADD FOREIGN KEY ("id_ronda") REFERENCES "san"."rondas" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "san"."pagos" ADD FOREIGN KEY ("id_usuario") REFERENCES "autenticacion"."usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "san"."pagos" ADD FOREIGN KEY ("id_metodo_pago_usuario") REFERENCES "finanzas"."metodos_pago_usuario" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "san"."pagos" ADD FOREIGN KEY ("id_moneda") REFERENCES "finanzas"."monedas" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "libro_mayor"."cuentas_contables" ADD FOREIGN KEY ("id_usuario") REFERENCES "autenticacion"."usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "libro_mayor"."cuentas_contables" ADD FOREIGN KEY ("id_moneda") REFERENCES "finanzas"."monedas" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "libro_mayor"."transacciones_contables" ADD FOREIGN KEY ("id_circulo") REFERENCES "san"."circulos" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "libro_mayor"."transacciones_contables" ADD FOREIGN KEY ("id_pago") REFERENCES "san"."pagos" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "libro_mayor"."asientos_contables" ADD FOREIGN KEY ("id_transaccion") REFERENCES "libro_mayor"."transacciones_contables" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "libro_mayor"."asientos_contables" ADD FOREIGN KEY ("id_cuenta") REFERENCES "libro_mayor"."cuentas_contables" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "autenticacion"."referidos" ADD FOREIGN KEY ("id_usuario_referente") REFERENCES "autenticacion"."usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "autenticacion"."referidos" ADD FOREIGN KEY ("id_usuario_referido") REFERENCES "autenticacion"."usuarios" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
